function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 19-Apr-2021 00:46:51

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'MarkerSize',8,'Marker','*','LineStyle','none');
set(plot1(1),'Color',[0 0 1]);
set(plot1(2),'Color',[1 0 0]);

% Create xlabel
xlabel('Cost');

% Create ylabel
ylabel('Satisfaction');

% Create title
title('Non-dominated Solutions (F_{1}) : Frontier');

